version: "3.9"

services:
  bot:
    build: .
    container_name: bot-jacks
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot.db:/app/bot.db
      - ./imagen:/app/imagen
